apiVersion: v1
kind: ConfigMap
metadata:
  name: cart
  namespace: roboshop1
  labels:
    component: cart
    project: roboshop1
    tier: app
data:
  REDIS_HOST: "redis"
  CATALOGUE_HOST: "catalogue"
  CATALOGUE_PORT: "8080"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: roboshop1
  # deployment labels
  labels:
    component: cart
    project: roboshop1
    tier: app
spec:
  replicas: 1
  # These are the labels replica set use to create pod replicas, this should match pod labels
  selector:
    matchLabels:
      component: cart
      project: roboshop1
      tier: app
  # This is pod definition
  template:
    metadata:
      labels:
        component: cart
        project: roboshop1
        tier: app
    spec:
      containers:
      - name: cart
        image: samrin357/cart:v1
        envFrom:
        - configMapRef:
            name: cart
---
apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: roboshop1
  labels:
    component: cart
    project: roboshop1
    tier: app
spec:
  selector:
    component: cart
    project: roboshop1
    tier: app
  ports:
  - protocol: TCP
    port: 8080 # service port
    targetPort: 8080 # container por