apiVersion: v1
kind: ConfigMap
metadata:
  name: user
  namespace: roboshop1
  labels:
    component: user
    project: roboshop1
    tier: app
data:
  MONGO_URL: "mongodb://mongodb:27017/users"
  REDIS_URL: "redis://redis:6379"
  MONGO: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: roboshop1
  # deployment labels
  labels:
    component: user
    project: roboshop1
    tier: app
spec:
  replicas: 1
  # These are the labels replica set use to create pod replicas, this should match pod labels
  selector:
    matchLabels:
      component: user
      project: roboshop1
      tier: app
  # This is pod definition
  template:
    metadata:
      labels:
        component: user
        project: roboshop1
        tier: app
    spec:
      containers:
      - name: user
        image: samrin357/user:v1
        envFrom:
        - configMapRef:
            name: user
---
apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: roboshop1
  labels:
    component: user
    project: roboshop1
    tier: app
spec:
  selector:
    component: user
    project: roboshop1
    tier: app
  ports:
  - protocol: TCP
    port: 8080 # service port
    targetPort: 8080 # container port